-- CreateTable
CREATE TABLE "document_types" (
    "id" TEXT NOT NULL,
    "org_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "document_types_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "document_types_org_id_idx" ON "document_types"("org_id");

-- CreateIndex
CREATE UNIQUE INDEX "document_types_org_id_name_key" ON "document_types"("org_id", "name");

-- AddForeignKey
ALTER TABLE "document_types" ADD CONSTRAINT "document_types_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Seed the default type list for every org that already exists - orgs
-- created from here on get the same defaults from createOrganization.ts.
-- The id uses a hash-of-randomness cast to uuid rather than gen_random_uuid(),
-- since this project's datasource only declares the postgis extension (ids
-- are otherwise generated by Prisma's client, never the database).
INSERT INTO "document_types" ("id", "org_id", "name", "enabled", "created_at")
SELECT (md5(random()::text || clock_timestamp()::text || o."id" || t."name"))::uuid, o."id", t."name", true, CURRENT_TIMESTAMP
FROM "organizations" o
CROSS JOIN (
    VALUES
        ('Invoice payable'),
        ('Invoice receivable'),
        ('Letter'),
        ('Other'),
        ('Police report'),
        ('Proposal'),
        ('Purchase order'),
        ('Receipt')
) AS t("name");

-- AlterTable
-- Backfilled below so any pre-existing documents stay valid; every future
-- insert supplies a real doc type and the levee's current year directly.
ALTER TABLE "documents" ADD COLUMN "doc_type_id" TEXT;
ALTER TABLE "documents" ADD COLUMN "year" INTEGER;
ALTER TABLE "documents" ADD COLUMN "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE "documents" d
SET "doc_type_id" = dt."id",
    "year" = EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER
FROM "levees" l
JOIN "document_types" dt ON dt."org_id" = l."org_id" AND dt."name" = 'Other'
WHERE d."levee_id" = l."id";

ALTER TABLE "documents" ALTER COLUMN "doc_type_id" SET NOT NULL;
ALTER TABLE "documents" ALTER COLUMN "year" SET NOT NULL;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_doc_type_id_fkey" FOREIGN KEY ("doc_type_id") REFERENCES "document_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AlterIndex
-- Superseded by the composite index below - leveeId-only lookups are still
-- served by its leftmost prefix.
DROP INDEX "documents_levee_id_idx";

-- CreateIndex
CREATE INDEX "documents_levee_id_year_idx" ON "documents"("levee_id", "year");

-- AlterTable
ALTER TABLE "levees" ADD COLUMN "current_doc_year" INTEGER;

UPDATE "levees" SET "current_doc_year" = EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER;

ALTER TABLE "levees" ALTER COLUMN "current_doc_year" SET NOT NULL;

-- AlterTable
ALTER TABLE "people" ADD COLUMN "can_delete_documents" BOOLEAN NOT NULL DEFAULT false;
